GET https://yandex.ru

###
POST https://www.google.ru/search?q=%D1%87%D1%82%D0%BE+%D1%82%D0%B0%D0%BA%D0%BE%D0%B5+api&newwindow=1&source=hp&ei=KXb0Y9nhOZXQqwGQrb3YCA&iflsig=AK50M_UAAAAAY_SEObwOlTE08GHFspMA-eHVLtX961eq&ved=0ahUKEwiZmqaAj6b9AhUV6CoKHZBWD4sQ4dUDCAg&uact=5&oq=%D1%87%D1%82%D0%BE+%D1%82%D0%B0%D0%BA%D0%BE%D0%B5+api&gs_lcp=Cgdnd3Mtd2l6EAMyCwgAEIAEELEDEIMBMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOggIABCABBCxAzoFCC4QgAQ6CAguEIAEELEDOggILhCxAxCDAToICAAQsQMQgwE6DQgAEIAEELEDEIMBEAo6BwgAEIAEEAo6CggAEIAEELEDEAo6BAgAEANQAFiLKmCUMGgAcAB4AIABY4gBzwmSAQIxM5gBAKABAQ&sclient=gws-wiz
